sudo: required

services:
  - docker

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t udalov/standard .

  - export VERSION=`docker run -it udalov/standard standardrb -v | tr -d '\r'`;
  - docker build -t udalov/standard:$VERSION .

  - docker run -v "$PWD:/app" -it udalov/standard standardrb test/test.rb

  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker push udalov/rubocop:latest;
      docker push udalov/rubocop:$VERSION;
    fi
